name: Emscripten
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash -e -l {0}
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Emscripten
            os: ubuntu-24.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: install mamba
      uses: mamba-org/setup-micromamba@main
      with:
        environment-file: environment-wasm-build.yml
        init-shell: bash
        environment-name: sparrow-wasm-build

    - name: Setup default Build Type on *nux
      if: ${{ runner.os != 'windows' }}
      run: |
        echo "ncpus=$(nproc --all)" >> $GITHUB_ENV

    - name: Build sparrow
      shell: bash -l {0}
      run: |
        micromamba create -f environment-wasm-host.yml --platform=emscripten-wasm32

        mkdir build
        pushd build

        export BUILD_PREFIX=$MAMBA_ROOT_PREFIX/envs/sparrow-wasm-build
        export PREFIX=$MAMBA_ROOT_PREFIX/envs/sparrow-wasm-host
        export SYSROOT_PATH=$BUILD_PREFIX/opt/emsdk/upstream/emscripten/cache/sysroot

        emcmake cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_FIND_ROOT_PATH=$PREFIX \
          -DCMAKE_INSTALL_PREFIX=$PREFIX \
          -DBUILD_EXAMPLES=OFF \
          -DBUILD_TESTS=ON \
          -DBUILD_DOCS=OFF \
          -DSYSROOT_PATH=$SYSROOT_PATH \
          ..

        emmake make -j ${{ env.ncpus }} install

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '23.x'

    - name: Run tests
      shell: bash
      working-directory: build/bin/Release
      run: |
        node --version
        node ./test_sparrow_lib.js
